annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.7.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
- name: zookeeper
  condition: zookeeper.enabled
  repository: https://charts.bitnami.com/bitnami
  version: 6.x.x
- name: kafdrop
  condition: kafdrop
description: Apache Kafka is a distributed streaming platform.
keywords:
- kafka
- kafdrop
- zookeeper
- streaming
- producer
- consumer
maintainers:
- email: mustwin@kakao.com
  name: donghoon-khan
name: kafka
sources:
- https://github.com/bitnami/bitnami-docker-kafka
- https://github.com/donghoon-khan/helm-charts
- https://kafka.apache.org/
version: 12.9.5
